language: go
sudo: false
go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
matrix:
  allow_failures:
    - go: tip
script:
  - make dependencies
  - make check
  - make test
  - make test-race
after_success:
  - make darwin
  - make linux